skip_tags: true
image: Visual Studio 2017
configuration: Release

install:
  - cinst gitversion.portable
  - cinst opencover.portable
  - cinst codecov
  - nuget restore
  - ps: gitversion /l console /output buildserver

on_failure:
  - ps: 7z a "WorkingTree.zip"
  - ps: Push-AppveyorArtifact WorkingTree.zip
  
dotnet_csproj:
  patch: true
  file: '**\phirSOFT.TopologicalComparison.csproj'
  version: $(GitVersion_FullSemVer)
  package_version: $(GitVersion_FullSemVer)
  assembly_version: $(GitVersion_AssemblySemVer)
  file_version: $(GitVersion_AssemblySemVer)
  informational_version: $(GitVersion_FullSemVer)
  
build:
  publish_nuget: true
  publish_nuget_symbols: true
  include_nuget_references: true
  parallel: true
  verbosity: minimal
  
test_script:
-OpenCover.Console.exe -register:user -target:"C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\MSTest.exe" -targetargs:"/testcontainer:.\phirSOFT.ConstraintedComparisonTests\bin\Release\phirSOFT.ConstraintedComparisonTests.dll"  -output:".\phirSOFT_TopologicalComparisonCoverage.xml" 
- nunit3-console C:\projects\phirsoft-topologicalcomparison\phirSOFT.ConstraintedComparisonTests\bin\Release\phirSOFT.ConstraintedComparisonTests.dll --result=phirSOFT_TopologicalComparisonCoverage.xml
- codecov -f "phirSOFT_TopologicalComparisonCoverage.xml"
deploy:
- provider: NuGet
  api_key:
    secure: lniRR37hIMpfCUlRXhQ1YmLKosIiuaNjAq2GyRcOefpsKtuqum2ZXeUpbeDYLit8
  on:
    branch: master

- provider: GitHub
  auth_token:
    secure: VqjJ8FyJ7cTc3GyeGVEr1oo/WChSp2+4iEgflkWN3tM6HUc+BdEHK5PNDtD9+7kg
  on:
    branch: master
