skip_tags: true
image: Visual Studio 2022
configuration: Release
environment:
  CODECOV_TOKEN:
    secure: p9Hx0XQTBj4cKDs0EiaZJtbrBEyDWK+pOP89zIQtdtH3OkJDgIeCFA1t2Dufh5FQ

install:
  - cinst gitversion.portable
  - cinst opencover.portable
  - cinst codecov
  - dotnet restore
  - ps: gitversion /l console /output buildserver

on_failure:
  - ps: 7z a "WorkingTree.zip"
  - ps: Push-AppveyorArtifact WorkingTree.zip
  
dotnet_csproj:
  patch: true
  file: '**\phirSOFT.TopologicalComparison.csproj'
  version: $(GitVersion_FullSemVer)
  package_version: $(GitVersion_FullSemVer)
  assembly_version: $(GitVersion_AssemblySemVer)
  file_version: $(GitVersion_AssemblySemVer)
  informational_version: $(GitVersion_FullSemVer)
  
build:
  publish_nuget: true
  publish_nuget_symbols: true
  include_nuget_references: true
  parallel: true
  verbosity: minimal
  
test_script:
- OpenCover.Console.exe -register:user -target:"C:\Program Files\Microsoft Visual Studio\2022\Community\Common7\IDE\IDE\MSTest.exe" -targetargs:"/testcontainer:.\phirSOFT.ConstraintedComparisonTests\bin\Release\phirSOFT.ConstraintedComparisonTests.dll"  -output:".\phirSOFT_TopologicalComparisonCoverage.xml" 
- codecov -f "phirSOFT_TopologicalComparisonCoverage.xml"
deploy:
- provider: NuGet
  api_key:
    secure: KKa4UFVvnawpDty4xTpIc3rHYAJ34cZkhMdCiNVJFQhzTVenLCQhGWgZajLreNA2
  on:
    branch: master

- provider: GitHub
  auth_token:
    secure: VqjJ8FyJ7cTc3GyeGVEr1oo/WChSp2+4iEgflkWN3tM6HUc+BdEHK5PNDtD9+7kg
  on:
    branch: master

skip_commits:
  files:
  - appveyor.yml
